---
title: "Lower the rim: Dunking and Star Power in the WNBA"
subtitle: "Is it the entertainment value of a game that drives its viewership?"
author: 
  - Sehar Bajwa
thanks: "Code and data are available at: https://github.com/SEHB2012/WNBA"
date: today
date-format: long
abstract: "Shaquille O'Neal's proposal to level the playing field between the WNBA and NBA by lowering the rim incites debate on the factors influencing the WNBA's success. This paper examines whether star power and entertainment value or emotional team allegiances drive viewership. Using a linear regression model, factors such as dunking, three-point shooting, star presence, and team performance are analyzed in both leagues to uncover insights in sports consumer behavior and revenue generation."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction

You think if we lower the rim so y'all can dunk like we dunk that would give y'all more oomph than you already have?"
Shaquille O'Neal 

This suggestion to 'equalise' the playing field amongst the WNBA and the NBA incensed and polarised opinion, but does drive another question: Is the lack of star power and 'oomph' the missing factor in WNBA's lukewarm success as a franchise? There have been only 37 dunks in WNBA's history, while in the better known counterpart, it is an everyday occurance. I therefore ask the question of whether it is 'star power'  and the entertainment value of a game that drives viewership, or is it just emotional investments in teams themselves? To answer this dilemma, I used a linear regression model to explore the influence of various factors such as dunking, three-point shooting, star presence, and team performance on team gate revenue in the NBA, and try to draw similar parallels in the WNBA. 



# References


